[package]
name = "m6-pal"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
m6-common = { workspace = true }
once_cell_no_std = { workspace = true }
fdt = "0.1"
